[project]
name = "colonyscanalyser"
version = "0.6.2"
description = "An image analysis tool for measuring microorganism colony growth"
readme = "README.md"
license = { text = "GPL-3.0" }
authors = [{ name = "Erik White" }]
requires-python = ">=3.13"
dependencies = [
    "numpy >= 1.18",
    "matplotlib",
    "scikit-image >= 0.25",
    "imreg-dft",
    "webcolors",
    "opencv-python>=4.11.0.86",
    "opencv-python-headless>=4.11.0.86",
]

[project.scripts]
colonyscanalyser = "colonyscanalyser.main:main"
scanalyser = "colonyscanalyser.main:main"

[project.optional-dependencies]
dev = ["pytest", "ruff", "pyright"]
test = ["pytest"]

[build-system]
requires = ["uv_build>=0.7.3,<0.8.0"]
build-backend = "uv_build"

# Ruff configuration
[tool.ruff]
line-length = 88
extend-exclude = ["build", "dist", ".eggs", "*.egg-info"]

[tool.ruff.lint]
ignore = []

[dependency-groups]
dev = ["pytest>=8.4.1"]
